### ISSUE TITLE
Linkedin Share not supported

### ISSUE THREAD

**Issue by ram-wappnet** [keval-devani/custom_social_share#4]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method linkedin on channel custom_social_share)

**Comment by keval-devani** [comment]
@ram-wappnet, thanks for reporting issue. I didn't found share link/url of Linkedin for iOS. If you know please share here here I'll update in plugin. PR are also welcome.

**Comment by ram-wappnet** [comment]
this issue is also in android

**Comment by keval-devani** [comment]
This bug is fixed now.

**Comment by ram-wappnet** [comment]
> This bug is fixed now.



> @ram-wappnet, thanks for reporting issue. I didn't found share link/url of Linkedin for iOS. If you know please share here here I'll update in plugin. PR are also welcome.

for ios, I have written code in Swift to open the default system share dialog with open LinkedIn but I don't know if it's working or not because I don't have mac

**Comment by keval-devani** [comment]
Please share here I will test the code.
