### ISSUE TITLE
Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by ram-wappnet** [keval-devani/custom_social_share#6]
pub-cache/hosted/pub.dev/custom_social_share-1.0.5/android/src/main/kotlin/com/kd/custom_social_share/CustomSocialSharePlugin.kt: (69, 31): Type mismatch: inferred type is String? but String was expected
pub-cache/hosted/pub.dev/custom_social_share-1.0.5/android/src/main/kotlin/com/kd/custom_social_share/CustomSocialSharePlugin.kt: (69, 36): Type mismatch: inferred type is String? but String was expected

 What went wrong:
Execution failed for task ':custom_social_share:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by keval-devani** [comment]
I updated code and error is fixed

**Comment by ram-wappnet** [comment]
still i have same issue

**Comment by keval-devani** [comment]
Please check new version.

**Comment by newputtipong** [comment]
the issue still there

**Comment by keval-devani** [comment]
Please check the latest version. It fixed now.
