### ISSUE TITLE
pub-cache/hosted/pub.dev/custom_social_share-1.0.5/android/src/main/kotlin/com/kd/custom_social_share/CustomSocialSharePlugin.kt: (69, 31): Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by nguyenquynh201** [keval-devani/custom_social_share#7]
pub-cache/hosted/pub.dev/custom_social_share-1.0.5/android/src/main/kotlin/com/kd/custom_social_share/CustomSocialSharePlugin.kt: (69, 31): Type mismatch: inferred type is String? but String was expected
pub-cache/hosted/pub.dev/custom_social_share-1.0.5/android/src/main/kotlin/com/kd/custom_social_share/CustomSocialSharePlugin.kt: (69, 36): Type mismatch: inferred type is String? but String was expected

What went wrong:
Execution failed for task ':custom_social_share:compileDebugKotlin'.

**Comment by keval-devani** [comment]
It fixed now.
